# Generated by Django 4.0.4 on 2022-06-11 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Usuario')),
                ('nombreusuario', models.CharField(max_length=100, verbose_name='Nombre Usuario')),
                ('correousuario', models.CharField(max_length=200, verbose_name='Correo Usuario')),
                ('contrasenausuario', models.CharField(max_length=50, verbose_name='Contraseña Usuario')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
