# Generated by Django 4.0.5 on 2022-06-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='aviso',
            field=models.BooleanField(verbose_name='Acepto Terminos y Condiciones'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='fecha_enviado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'Consulta'], [1, 'Sugerencia'], [2, 'Reclamo'], [3, 'No deseo Responder'], [4, 'otro']]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
