# Generated by Django 4.0.4 on 2022-06-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marca_producto_remove_usuario_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagem',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
