# Generated by Django 4.0.4 on 2022-06-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagem',
            new_name='imagen',
        ),
    ]
