# Generated by Django 4.0.5 on 2022-06-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_imagem_producto_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marca',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='nombreMarca',
            new_name='nombreTipo',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
    ]
