# Generated by Django 4.0.5 on 2022-06-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_marca_tipo_rename_marca_producto_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='segundadescripcion',
            field=models.TextField(default=7),
            preserve_default=False,
        ),
    ]
