# Generated by Django 4.0.5 on 2022-06-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20220614_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_fabricacion',
            new_name='fecha_ingresado',
        ),
    ]
